name: scubanews
favicon: null
layout_spectrum: 0.7877144885715097
typography_spectrum: 0.5572426025755703
title: Scuba News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17671007849276066
  lightness: 0.996204886585474
  saturation: 0.5447273817844689
  rhythmicContrast: 0.638975870097056
purpose: []
