name: Scuba News
favicon: null
layout_spectrum: 0.7877144885715097
typography_spectrum: 0.5572426025755703
title: Scuba News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171823'
    - '#53628b'
    - '#8796ac'
    - '#dcdcbf'
    - '#ce9e81'
  brandStrength: 0.17671007849276066
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
